/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tic.tac.toe;

import javax.swing.JOptionPane;
import javax.swing.JButton;
//import tic.tac.toe.CustomInputDialog;

public class Game_UI extends javax.swing.JFrame {

    private int player_turn = 0;
    private String[] board = new String[9];
    //String text1, text2, text3, text4, text5, text6, text7, text8, t9;
    
    public Game_UI() {
        /*this.t9 = "h";
        this.text8 = "g";
        this.text7 = "f";
        this.text6 = "e";
        this.text5 = "d";
        this.text4 = "c";
        this.text3 = "b";
        this.text2 = "";
        this.text1 = "a";*/
        
        initComponents();
        initializeBoard();
    }
    
    private void initializeBoard() {
        for (int i = 0; i < 9; i++) {
            board[i] = "";
        }
    }
    
    private void updateButton(JButton button, int index) {
        if (board[index].isEmpty()) {
            board[index] = (player_turn == 0) ? "X" : "O";
            button.setText(board[index]);
            player_turn = 1 - player_turn; // Alternar entre 0 y 1
            checkForWinner();
        }
    }
    private void checkForWinner() {
        int[][] winningCombinations = {
            {0, 1, 2}, {3, 4, 5}, {6, 7, 8}, // Filas
            {0, 3, 6}, {1, 4, 7}, {2, 5, 8}, // Columnas
            {0, 4, 8}, {2, 4, 6} // Diagonales
        };

        for (int[] combination : winningCombinations) {
            String marker = board[combination[0]];
            if (!marker.isEmpty() && board[combination[1]].equals(marker) && board[combination[2]].equals(marker)) {
                JOptionPane.showMessageDialog(null, "¡" + marker + " gana!");
                resetGame();
                return;
            }
        }
        
        boolean isTie = true;
        for (String cell : board) {
            if (cell.isEmpty()) {
                isTie = false;
                break;
            }
        }

        if (isTie) {
            JOptionPane.showMessageDialog(null, "¡Empate!");
            resetGame();
        }
    }
    
    private void resetGame() {
        int option = 0;
        do{
            String userInput = JOptionPane.showInputDialog("Desea continuar jugando?\n(1) Continuar.\n(2) Salir");
        if (userInput != null && !userInput.isEmpty()) {
            try {
                option = Integer.parseInt(userInput);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese una opción válida.");
            }
        } else {
            // El usuario ha cancelado el diálogo, puedes manejarlo aquí si es necesario
            // Por ejemplo, puedes considerarlo como una opción de salida.
            option = 2; // Salir por defecto
        }
            /*CustomInputDialog dialog = new CustomInputDialog(this, "Desea continuar jugando?\n(1) Continuar.\n(2) Salir");
            String userInput = dialog.showDialog();
            option = Integer.parseInt(userInput);*/
            /*option = Integer.parseInt(JOptionPane.showInputDialog("""
                                                                  Desea continuar jugando?
                                                                  (1) Continuar.
                                                                  (2) Salir."""));*/
        }while(option != 1 && option != 2);
        if (option == 1){
            for (int i = 0; i < 9; i++) {
            board[i] = "";
            JButton button = getButtonByIndex(i);
            button.setText("");
        }
        player_turn = 0;
        } else if (option == 2){
            System.exit(0);
        } else{
            JOptionPane.showMessageDialog(null, "Ingrese una opción válida.");
        }
    }
    
    private JButton getButtonByIndex(int index) {
        switch (index) {
            case 0:
                return B1;
            case 1:
                return B2;
            case 2:
                return B3;
            case 3:
                return B4;
            case 4:
                return B5;
            case 5:
                return B6;
            case 6:
                return B7;
            case 7:
                return B8;
            case 8:
                return B9;
            default:
                return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        B1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        B7 = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        B9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        B1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        B1.setText("");
        B1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B1MouseClicked(evt);
            }
        });
        jPanel1.add(B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 100));

        B2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        B2.setText("");
        B2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B2MouseClicked(evt);
            }
        });
        jPanel1.add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 130, 100));

        B3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        B3.setText("");
        B3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B3MouseClicked(evt);
            }
        });
        jPanel1.add(B3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 130, 100));

        B4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        B4.setText("");
        B4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B4MouseClicked(evt);
            }
        });
        jPanel1.add(B4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 130, 100));

        B5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        B5.setText("");
        B5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B5MouseClicked(evt);
            }
        });
        jPanel1.add(B5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 130, 100));

        B6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        B6.setText("");
        B6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B6MouseClicked(evt);
            }
        });
        jPanel1.add(B6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 130, 100));

        B7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        B7.setText("");
        B7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B7MouseClicked(evt);
            }
        });
        jPanel1.add(B7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 130, 100));

        B8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        B8.setText("");
        B8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B8MouseClicked(evt);
            }
        });
        jPanel1.add(B8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 130, 100));

        B9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        B9.setText("");
        B9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B9MouseClicked(evt);
            }
        });
        jPanel1.add(B9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 130, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void B1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B1MouseClicked
        /*text1 = B1.getText();
        if (player_turn == 0 && text1.equals("")){
            B1.setText("X");
            win(text1, text2, text3, text4, text5, text6, text7, text8, t9);
            player_turn = 1;
        }else if (player_turn == 1 && text1.equals("")){
            B1.setText("O");
            win(text1, text2, text3, text4, text5, text6, text7, text8, t9);
            player_turn = 0;
        } else{
        }*/
        updateButton(B1, 0);
    }//GEN-LAST:event_B1MouseClicked

    private void B2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B2MouseClicked
        /*text2 = B2.getText();
        if (player_turn == 0 && text2.equals("")){
            B2.setText("X");
            win(text1, text2, text3, text4, text5, text6, text7, text8, t9);
            player_turn = 1;
        }else if (player_turn == 1 && text2.equals("")){
            B2.setText("O");
            win(text1, text2, text3, text4, text5, text6, text7, text8, t9);
            player_turn = 0;
        } else{
        }*/
        updateButton(B2, 1);
    }//GEN-LAST:event_B2MouseClicked

    private void B3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B3MouseClicked
        /*text3 = B3.getText();
        if (player_turn == 0 && text3.equals("")){
            B3.setText("X");
            win(text1, text2, text3, text4, text5, text6, text7, text8, t9);
            player_turn = 1;
        }else if (player_turn == 1 && text3.equals("")){
            B3.setText("O");
            win(text1, text2, text3, text4, text5, text6, text7, text8, t9);
            player_turn = 0;
        } else{
        }*/
        updateButton(B3, 2);
    }//GEN-LAST:event_B3MouseClicked

    private void B4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B4MouseClicked
        /*text4 = B4.getText();
        if (player_turn == 0 && text4.equals("")){
            B4.setText("X");
            win(text1, text2, text3, text4, text5, text6, text7, text8, t9);
            player_turn = 1;
        }else if (player_turn == 1 && text4.equals("")){
            B4.setText("O");
            win(text1, text2, text3, text4, text5, text6, text7, text8, t9);
            player_turn = 0;
        } else{
        }*/
        updateButton(B4, 3);
    }//GEN-LAST:event_B4MouseClicked

    private void B5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B5MouseClicked
        /*text5 = B5.getText();
        if (player_turn == 0 && text5.equals("")){
            B5.setText("X");
            win(text1, text2, text3, text4, text5, text6, text7, text8, t9);
            player_turn = 1;
        }else if (player_turn == 1 && text5.equals("")){
            B5.setText("O");
            win(text1, text2, text3, text4, text5, text6, text7, text8, t9);
            player_turn = 0;
        } else{
        }*/
        updateButton(B5, 4);
    }//GEN-LAST:event_B5MouseClicked

    private void B6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B6MouseClicked
        /*text6 = B6.getText();
        if (player_turn == 0 && text6.equals("")){
            B6.setText("X");
            player_turn = 1;
        }else if (player_turn == 1 && text6.equals("")){
            B6.setText("O");
            player_turn = 0;
        } else{
        }*/
        updateButton(B6, 5);
    }//GEN-LAST:event_B6MouseClicked

    private void B7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B7MouseClicked
        /*text7 = B7.getText();
        if (player_turn == 0 && text7.equals("")){
            B7.setText("X");
            win(text1, text2, text3, text4, text5, text6, text7, text8, t9);
            player_turn = 1;
        }else if (player_turn == 1 && text7.equals("")){
            B7.setText("O");
            win(text1, text2, text3, text4, text5, text6, text7, text8, t9);
            player_turn = 0;
        } else{
        }*/
        updateButton(B7, 6);
    }//GEN-LAST:event_B7MouseClicked

    private void B8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B8MouseClicked
        /*text8 = B8.getText();
        if (player_turn == 0 && text8.equals("")){
            B8.setText("X");
            win(text1, text2, text3, text4, text5, text6, text7, text8, t9);
            player_turn = 1;
        }else if (player_turn == 1 && text8.equals("")){
            B8.setText("O");
            win(text1, text2, text3, text4, text5, text6, text7, text8, t9);
            player_turn = 0;
        } else{
        }*/
        updateButton(B8, 7);
    }//GEN-LAST:event_B8MouseClicked

    private void B9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B9MouseClicked
        /*t9 = B9.getText();
        if (player_turn == 0 && t9.equals("")){
            B9.setText("X");
            win(text1, text2, text3, text4, text5, text6, text7, text8, t9);
            player_turn = 1;
        }else if (player_turn == 1 && t9.equals("")){
            B9.setText("O");
            win(text1, text2, text3, text4, text5, text6, text7, text8, t9);
            player_turn = 0;
        } else{
        }
        win(text1, text2, text3, text4, text5, text6, text7, text8, t9);*/
        updateButton(B9, 8);
    }//GEN-LAST:event_B9MouseClicked
    
    public void win(String text1, String text2, String text3, String text4, String text5, String text6, String text7, String text8, String t9) {
    // Arreglo para almacenar las marcas en el tablero
    String[] board = {text1, text2, text3, text4, text5, text6, text7, text8, t9};

    // Combinaciones ganadoras (índices del tablero)
    int[][] winningCombinations = {
        {0, 1, 2}, {3, 4, 5}, {6, 7, 8}, // Filas
        {0, 3, 6}, {1, 4, 7}, {2, 5, 8}, // Columnas
        {0, 4, 8}, {2, 4, 6} // Diagonales
    };

    // Verifica si alguno de los jugadores ha ganado
    for (int[] combination : winningCombinations) {
        String marker = board[combination[0]];
        if (!marker.equals("") && board[combination[1]].equals(marker) && board[combination[2]].equals(marker)) {
            JOptionPane.showMessageDialog(null, "¡" + marker + " gana!");
            return; // El juego ha terminado
        }
    }

    // Si no hay ganador y todas las casillas están llenas, es un empate
    boolean isTie = true;
    for (String cell : board) {
        if (cell.equals("")) {
            isTie = false;
            break;
        }
    }

    if (isTie) {
        JOptionPane.showMessageDialog(null, "¡Empate!");
    }
}

    
   /* public void win(String text1, String text2, String text3, String text4, String text5, String text6, String text7, String text8, String t9){
        if (((text1.equals("X") && text2.equals("X") && text3.equals("X")) 
                || (text1.equals("X") && text5.equals("X") && t9.equals("X")) 
                || (text3.equals("X") && text5.equals("X") && text7.equals("X")) 
                || (text4.equals("X") && text5.equals("X") && text6.equals("X")) 
                || (text7.equals("X") && text8.equals("X") && t9.equals("X")) 
                || (text1.equals("X") && text4.equals("X") && text7.equals("X")) 
                || (text2.equals("X") && text5.equals("X") && text8.equals("X")) 
                || (text3.equals("X") && text6.equals("X") && t9.equals("X")))
                || ((text1.equals("O") && text2.equals("O") && text3.equals("O")) 
                || (text1.equals("O") && text5.equals("O") && t9.equals("O")) 
                || (text3.equals("O") && text5.equals("O") && text7.equals("O")) 
                || (text4.equals("O") && text5.equals("O") && text6.equals("O")) 
                || (text7.equals("O") && text8.equals("O") && t9.equals("O")) 
                || (text1.equals("O") && text4.equals("O") && text7.equals("O")) 
                || (text2.equals("O") && text5.equals("O") && text8.equals("O")) 
                || (text3.equals("O") && text6.equals("O") && t9.equals("O")))){
            JOptionPane.showMessageDialog(null, "You win");
        } else{
            
        }
    }*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game_UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JButton B8;
    private javax.swing.JButton B9;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
